### ISSUE TITLE
(FunctionClauseError) no function clause matching in Quantum.Normalizer.normalize_task/1

### ISSUE THREAD

**Issue by dokuzbir** [quantum-elixir/quantum-core#340]
Elixir -v = 1.6.4
phoenix -v = 1.3.2
quantum-core -v = 2.2.7
timex -v = 3.2.2
gen_stage -v = 0.13.1

I get output "working" when mix phx.server but server suddenly closes

```
config :my_app, MyApp.Scheduler,
 jobs: [
    # Every minute
   {"* * * * *",      IO.puts("working")},
  ]

```
```
[info] Running MyAppWeb.Endpoint with Cowboy using http://0.0.0.0:4000
[info] Application saha_time exited: MyApp.Application.start(:normal, []) returned an error: shutdown: failed to start child: MyApp.Scheduler
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in Quantum.Normalizer.normalize_task/1
            (quantum) lib/quantum/normalizer.ex:86: Quantum.Normalizer.normalize_task(:ok)
            (quantum) lib/quantum/normalizer.ex:68: Quantum.Normalizer.normalize_job_option/2
            (stdlib) lists.erl:1263: :lists.foldl/3
            (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
            (quantum) lib/quantum.ex:67: Quantum.runtime_config/3
            (quantum) lib/quantum/supervisor.ex:19: Quantum.Supervisor.init/1
            (stdlib) supervisor.erl:294: :supervisor.init/1
            (stdlib) gen_server.erl:365: :gen_server.init_it/2
            (stdlib) gen_server.erl:333: :gen_server.init_it/6
            (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
** (Mix) Could not start application saha_time: MyApp.Application.start(:normal, []) returned an error: shutdown: failed to start child: MyApp.Scheduler
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in Quantum.Normalizer.normalize_task/1
            (quantum) lib/quantum/normalizer.ex:86: Quantum.Normalizer.normalize_task(:ok)
            (quantum) lib/quantum/normalizer.ex:68: Quantum.Normalizer.normalize_job_option/2
            (stdlib) lists.erl:1263: :lists.foldl/3
            (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
            (quantum) lib/quantum.ex:67: Quantum.runtime_config/3
            (quantum) lib/quantum/supervisor.ex:19: Quantum.Supervisor.init/1
            (stdlib) supervisor.erl:294: :supervisor.init/1
            (stdlib) gen_server.erl:365: :gen_server.init_it/2
            (stdlib) gen_server.erl:333: :gen_server.init_it/6
            (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

**Comment by dokuzbir** [comment]
I was using wrong synxtax solved that {"* * * * *",   {IO, :puts, ["working"]}}
