### ISSUE TITLE
Improve tzdata Setup instructions

### ISSUE THREAD

**Issue by jean-smaug** [quantum-elixir/quantum-core#432]
👋 I'm using `3.0.0-rc` version and I'm facing an issue.

I can't modify the timezone even if if I'm using `timezone: "America/Chicago"` from the doc

```elixir
config :my_bot, MyBot.Scheduler,
  timezone: "Europe/Paris",
  jobs: [
    {"1 10 * * 1-5", {MyBot, :send_message, []}},
    {"0 8 * * *", {MyBot, :send_covid, []}}
  ]
```

Here are the logs.

```bash
13:28:47.016 [warn]  Timezone database not setup
 
13:28:47.024 [error] Invalid Timezone "Europe/Paris" provided for job #Reference<0.3764604614.3566206980.190193>.
 
13:28:47.024 [warn]  Timezone database not setup

13:28:47.024 [error] Invalid Timezone "Europe/Paris" provided for job #Reference<0.3764604614.3566206980.190172>.
 
13:28:47.049 [error] GenServer MyBot.Scheduler.ExecutionBroadcaster terminating
** (FunctionClauseError) no function clause matching in Quantum.ExecutionBroadcaster.sort_state/1
    (quantum 3.0.0-rc.3) lib/quantum/execution_broadcaster.ex:263: Quantum.ExecutionBroadcaster.sort_state(:ok)
    (quantum 3.0.0-rc.3) lib/quantum/execution_broadcaster.ex:147: Quantum.ExecutionBroadcaster.handle_event/2
    (quantum 3.0.0-rc.3) lib/quantum/execution_broadcaster.ex:80: anonymous fn/2 in Quantum.ExecutionBroadcaster.handle_events/3
    (elixir 1.10.2) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
    (quantum 3.0.0-rc.3) lib/quantum/execution_broadcaster.ex:79: Quantum.ExecutionBroadcaster.handle_events/3
    (gen_stage 1.0.0) lib/gen_stage.ex:2395: GenStage.consumer_dispatch/6
    (gen_stage 1.0.0) lib/gen_stage.ex:2574: GenStage.take_pc_events/3
    (stdlib 3.11.2) gen_server.erl:637: :gen_server.try_dispatch/4
```

Thx :)

**Comment by maennchen** [comment]
I guess it's because `tzdata` is not set up correctly. There should probably be more docs on this...

See https://github.com/lau/tzdata

```
config :elixir, :time_zone_database, Tzdata.TimeZoneDatabase
```

**Comment by jean-smaug** [comment]
Thx for your help, it's compiling now.

I'll see tomorrow if it's working in prod
